### ISSUE TITLE
formik

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#10]
<img width="358" alt="Screenshot 2023-02-26 at 18 49 43" src="https://user-images.githubusercontent.com/59687966/221427297-a6517d59-3fee-41ff-b6de-75bdd5227cf7.png">

Formik класний, але останнє його оновлення було 2 роки тому
Тож рекомендую спробувати React Hook Form

**Comment by apexi777** [comment]
Замінив на React Hook Form
