### ISSUE TITLE
NikeServices

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#11]
Тобі потрібно прибрати `NikeServices` а всю логіку з ного розкидати по компонентам
З ним багато проблем
1. Дані. Все що збережено в `NikeServices` знаходиться за межами реакту. А отже реакте не буде змінювати UI при зміні даних
2. Оптимізація. `const Service = new NikeServices();` - цей рядок буде виконуватись при кожному перендері `App.js`, зараз щастить і в він не перерендерюється, але навіть зберігати дані в `NikeServices` не вийде, тому що він буде створюватись кожного разу
3. Мутації. Зміни даних (масиву) відбуваються через мутацію, що спричить багато проблем
4. `this.visibleData` це має бути в стейті
5. Ускладненість, якщо прибрати `NikeServices` з код стане набагато простіший

**Comment by apexi777** [comment]
Прибрав NikeServices
