### ISSUE TITLE
toggleFavorite

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#12]
```
if (JSON.stringify(elem.select) === '{}') {
    return {...elem, ...{select : selected}}
} else {
    return {...delete elem.select.favorite, ...elem };
}
```
ух
1. `JSON.stringify(elem.select) === '{}'` - дуже ненадійна перевірка. Перевіряй саме на ті значення які тобі потрібні.
Наприклад
`if (elem.select.favorite)`
або
`if ('favorite' in elem.select)`

2. `{...delete elem.select.favorite, ...elem };` - навіть не думав що так це може працювати але 
`delete element` -  повертає true або false а `{...true}` або `{...false}` -  це `{}`
Але так все одно краще не робити, винеси їх окремо

```
delete elem.select.favorite,
return elem;
```

**Comment by apexi777** [comment]
згоден
