### ISSUE TITLE
`chosenFavorite` в `CatalogItem.jsx`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#14]
`chosenFavorite` виглядає занадто складко. Набагато простіше було зберігати `true` або `false` в `isFasorite` і додати умову в рендері

```
className={`slider_menu_item_favorite ${isFasorite ? 'select' : ''}
```

**Comment by DmitriiMelnikOnix** [comment]
Теж саме стосується і `classes`

**Comment by DmitriiMelnikOnix** [comment]
І `filterMenuView` в `CatalogMenu.jsx`

**Comment by DmitriiMelnikOnix** [comment]
і `activeContent` в `Promo.jsx`

**Comment by apexi777** [comment]
дуже зручно) дякую
