### ISSUE TITLE
Оновлення стейту 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#18]
```
 const [filterMenuView, setFilterMenuView] = useState(false);
  
const toggleMenuFilter = () => {
  setFilterMenuView(!filterMenuView);
};
```
Якщо нове значення залежить від минулого значення - краще використовувати функцію для оновлення стейту. В функціональних компонентах теж

`setFilterMenuView((prev) => !prev);`

**Comment by apexi777** [comment]
Дякую, пофіксив
