### ISSUE TITLE
`setState`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#2]
це добре що ти використовуєш функція для зміни стейту, але
1. `setPrice(price => price = 0);` - в цьому випадку функція не потрібна. Краще записати так `setPrice(0);`. Функція потрібна лише тоді, коли нове значення стейту залежить від старого
2. `setCount(count-1);` - а тут напаки, краще зробити за допомогою функції
3. `setPrice(price => price = count * activePromo[0].price);` частина коду `price = ` зайва, так як потрібно лиш повернути з функції нове значення, а не переприсвоювати його. `setPrice(price => count * activePromo[0].price);` - так буде коректніше

**Comment by apexi777** [comment]
Дякую, підправив
