### ISSUE TITLE
`checkCurrencyPrice`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#23]
```
currency.forEach((element) => {
  const { cc, rate } = element;
  console.log('name', name);
  if (name === cc && name !== 'USD') {
    setPrice((Math.round((activePromo.price / rate) * usdRate)) * count);
  } else if (name === 'USD') {
    setPrice(activePromo.price * count);
  }
});
```

`setPrice` в `forEach` виглядає дуже підозріло. Краще знайти потрібний елемент за допомогою `find` після чого збережи ціну

**Comment by apexi777** [comment]
const desiredName = currency.find((item) => { return item.cc === name; });
    if (desiredName.cc === 'USD') {
      setPrice(activePromo.price * count);
    } else {
      setPrice((Math.round((activePromo.price / desiredName.rate) * usdRate)) * count);
    }
Дякую.
