### ISSUE TITLE
eslint-disable-next-line no-shadow

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#28]
Не вимикай правила, а шукай способи вирішення попередження

```
this.setState(({ showData }) => {
  const newArr = [...showData, newCards];
  return {
    showData: newArr
  };
});
```

тут буде достатньо лиш змінити назву
і використовуй короткі стрілочні функції

```
this.setState(({ showData: prevShowData }) => ({
  showData: [...prevShowData, newCards]
}));
```

**Comment by apexi777** [comment]
Зрозумів, не міг допетрати як пофіксити відразу, тому включив. дальніше тільки фікс!)
