### ISSUE TITLE
SliderItem

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#33]
Краще не зберігати `src` який приходить з пропсу в стейт. Якщо пропс зміниться, компонент продовже використати старе значення.

Краще записати якось так

```javascript

const {error} = this.state

return (
  <SlideItemView 
    src={!!error ? errorImage : src}
  />
);
```

**Comment by apexi777** [comment]
дякую, навіть краще читаєтья
