### ISSUE TITLE
Стрілочні функції

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#38]
```
{
  menuItems.map(({ name, id }) => {
    return (
      <HeaderNav 
        key={id}
        name={name}
      />
    );
  })
  }
```

В стрілочних функція, особливо в JSX, якщо можна обійтись без `return`, то краще його не добавати, тоді код виглядає більше схожим на html, трохи приємніше довитись

**Comment by apexi777** [comment]
пофіксив
