### ISSUE TITLE
Price: High-Low

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#40]
https://github.com/apexi777/onix_app_react/issues/35

Можливо ще не залив, в мене ще версія без констант
<img width="559" alt="Знімок екрана 2023-04-12 о 19 55 21" src="https://user-images.githubusercontent.com/59687966/231543034-063f625a-f9db-455e-9d79-e957730bb300.png">

**Comment by apexi777** [comment]
не встиг, пофіксив вже в функціональних
