### ISSUE TITLE
setSelectState

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#46]
```javascript
const setSelectState = useCallback((value) => {
    setSelect(value);
  }, [select]);
```
1. `select` не потрібно вказувати в залежностях, він ніяк не впливає на функцію `setSelect`
2. Можна взагалі не створювати функцію `setSelectState` а записати так 
```javascript
<Sorting
  setSelectState={setSelect}
/>
```

**Comment by apexi777** [comment]
Дякую, чудово
