### ISSUE TITLE
Умовний рендер

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#47]
```javascript
{shoes.length !== 0
  ? (
    <>
      <CatalogMenu />
      <Slider />
    </>
  )
  : null}
```

Зазвичай тернартний оператор використовується якщо потрібно обрати один з компонентів. А якщо компонент лише один і потрібно вирішити показувати його чи ні, то краще використовувати `&&`

```javascript
{!!shoes.length && (
  <>
    <CatalogMenu />
    <Slider />
  </>
)}
```

**Comment by apexi777** [comment]
Дякую, чудове рішення
