### ISSUE TITLE
langChange

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#48]
```javascript
 useEffect(() => {
    i18n.changeLanguage(lang);
  }, [lang]);
```

Такий варіант зміни мови не дуже гарний, якщо користувач буде на іншій сторінці цей useEffect може не відпрацювати. Краще створити функцію за допомогою `createAsyncThunk` і в ній викликати i18n.changeLanguage, а також привʼязати санк в `extraReducers` в `headerSlice`

**Comment by apexi777** [comment]
Трошки помучався, але розібрався в створенні createAsyncThunk
Дякую
