### ISSUE TITLE
indexOf

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#5]
```
 const secondaryData = items.filter(item => {
      return item.name.toLowerCase().indexOf(term.toLowerCase()) > -1
  })
```

`indexOf` - краще використовувати коли потрібен саме індекс, а якщо лише перевірити наявність можно використати `includes`

Тоді не потрібно буде порівнювати з -1

**Comment by apexi777** [comment]
Дякую за допомогу, підправив код
