### ISSUE TITLE
priceUpdate

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#51]
```javascript
  const activePromo = useSelector(selectorActivePromo);
  const count = useSelector(selectorCount);
  const currencyMenu = useSelector(selectorCurrencyMenu);

  // Оновлення обраного символу валюти
  useEffect(() => {
    dispatch(activeCharacterUpdate());
  }, [currencyMenu]);

  // Оновлення прайсу згідно з обраною валютою та кількістю товару
  useEffect(() => {
    dispatch(priceUpdate(activePromo.price));
  }, [count, currencyMenu]);
```

Тут можна використати інший підхід чим спростити код і його використання

Наразі ти дістаєш дані з стору, перевіряєш їх в `useEffect` після чого знову зберігаєш в стор. І якщо цей компонент не буде відрендерений то зʼявиться проблема з оновленням даних

Можна зробити простіше
Якщо написати складніший селектор
```javascript
selectorActiveCharacter = (state) => state.currencyMenu.filter((item) => item.select);
```
то незалежно від ніяких компонентів завжди можна діставати одразу потрібно дані, не зберігаючи додатково їх в редаксі
Те ж саме стосується і поля price, його можна підраховувати в селекторі

Ну і наступний рівень оптимізації - огорнути ці селектори в createSelector, щоб вони викликались лиши при зміні вхідних параметрів

**Comment by DmitriiMelnikOnix** [comment]
PS: можливо селектор потрібно буде ускладнити, я не впевнений що той що я написав підійде для твого прикладу

**Comment by apexi777** [comment]
Дякую, чудова оптимізація, візьму назамітку на подальшому для себе
