### ISSUE TITLE
`showPromo`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [apexi777/onix_app_react#9]
```
showPromo = (data) => {
    return data.filter(item => { return item.visibleOnPromo })
}
```
На скільки я зрозумів, тобі потрібно знайти елемент з `visibleOnPromo`, краще використати не `filter`, a `find`

find - поверне один елемент масиву

**Comment by DmitriiMelnikOnix** [comment]
PromoShowing все рівно відображає лише перший елемент

**Comment by apexi777** [comment]
Супер і код в дочірній компоненті гарніший став, без звернень до єлемента массива. Дякую!
